var TILE_COUNT = 3;

var TILE_SIZE = 64;
var DEFAULT_CANVAS_COLOR = 'black';//'rgb(83,86,44)';

var CANVAS_WIDTH = (TILE_SIZE * TILE_COUNT);
var CANVAS_HEIGHT = (TILE_SIZE * TILE_COUNT);


var BOARD_LEFT_OFFSET = (CANVAS_WIDTH / 2) - (TILE_SIZE * (TILE_COUNT / 2));
var BOARD_TOP_OFFSET = (CANVAS_HEIGHT / 2) - (TILE_SIZE * (TILE_COUNT / 2));
var BOARD_RIGHT_MARGIN = (BOARD_LEFT_OFFSET + (TILE_SIZE * TILE_COUNT));
var BOARD_BOTTOM_MARGIN = (BOARD_TOP_OFFSET + (TILE_SIZE * TILE_COUNT));

var ROW_BOARD_MASK_X = BOARD_LEFT_OFFSET - TILE_SIZE;
var ROW_BOARD_MASK_Y = BOARD_TOP_OFFSET;

var COL_BOARD_MASK_X = BOARD_LEFT_OFFSET;
var COL_BOARD_MASK_Y = BOARD_TOP_OFFSET - TILE_SIZE;

var TILE_FONT = '14px Lucida Console';
var MOUSE_CLICK_DELTA_THRESHOLD = 5;
var STRIP_TYPE = {ROW : 2, COL : 1, UNREGISTERED : 0};

var DUPLICATION_COUNT = 10;
var RANDOM_COUNT = TILE_COUNT * 200;
