const TILE_COUNT = 4;
const CANVAS_WIDTH = 480;
const CANVAS_HEIGHT = 480;
const TILE_SIZE = 64;
const DEFAULT_CANVAS_COLOR = 'black';//'rgb(83,86,44)';

const BOARD_LEFT_OFFSET = (CANVAS_WIDTH / 2) - (TILE_SIZE * (TILE_COUNT / 2));
const BOARD_TOP_OFFSET = (CANVAS_HEIGHT / 2) - (TILE_SIZE * (TILE_COUNT / 2));
const BOARD_RIGHT_MARGIN = (BOARD_LEFT_OFFSET + (TILE_SIZE * TILE_COUNT));
const BOARD_BOTTOM_MARGIN = (BOARD_TOP_OFFSET + (TILE_SIZE * TILE_COUNT));

const ROW_BOARD_MASK_X = BOARD_LEFT_OFFSET - TILE_SIZE;
const ROW_BOARD_MASK_Y = BOARD_TOP_OFFSET;

const COL_BOARD_MASK_X = BOARD_LEFT_OFFSET;
const COL_BOARD_MASK_Y = BOARD_TOP_OFFSET - TILE_SIZE;

const GAME_LOOP_INTERVAL = 200000;
const TILE_FONT = TILE_SIZE /4 +'px bold icon';
const MOUSE_CLICK_DELTA_THRESHOLD = 5;
const STRIP_TYPE = {ROW : 2, COL : 1, UNREGISTERED : 0};

const DUPLICATION_COUNT = 5;
